version: "2"
services:
  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      network:
        ipv4_address: 172.129.0.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp_root:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      network:
        ipv4_address: 172.129.0.5
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    restart: always
volumes:
  wp_root:
  db_data:
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.129.0.0/16
          gateway: 172.129.0.1